[target.x86_64-pc-windows-msvc]
linker = "lld-link"

rustflags = [
    "-C", "link-arg=/LIBPATH:/home/freedomleaker/.xwin/crt/lib/x86_64",
    "-C", "link-arg=/LIBPATH:/home/freedomleaker/.xwin/sdk/lib/um/x86_64",
    "-C", "link-arg=/LIBPATH:/home/freedomleaker/.xwin/sdk/lib/ucrt/x86_64",
    "-C", "link-arg=-nodefaultlib",
    "-C", "link-arg=-entry:fuck_you_reverse_engineer",
    "-C", "link-arg=-opt:ref,icf",
    "-C", "link-arg=-subsystem:console",
]